// Generated by CoffeeScript 1.10.0
import Gdx from 'gdx/Gdx';

/*
 * @JSName("gdx.graphics.g2d.BitmapFont")
 */
var BitmapFont;

BitmapFont = (function() {
  function BitmapFont(fontFile, region, integer1) {
    var dom, name;
    this.fontFile = fontFile;
    this.region = region;
    this.integer = integer1;
    name = this.fontFile.path.split('/').pop().split('.')[0];
    dom = (new DOMParser()).parseFromString(Gdx._resources[name].xhr.responseText, 'text/xml');
    this.face = dom.evaluate('/font/info/@face', dom, null, XPathResult.STRING_TYPE, null).stringValue;
    this.size = dom.evaluate('/font/info/@size', dom, null, XPathResult.STRING_TYPE, null).stringValue;
  }

  BitmapFont.prototype.setUseIntegerPositions = function(integer) {};

  BitmapFont.prototype.getWidth = function() {};

  BitmapFont.prototype.getHeight = function() {};

  BitmapFont.prototype.draw = function(batch, str, x, y) {
    var texture;
    texture = new PIXI.extras.BitmapText(str, {
      font: this.size + "px " + this.face,
      align: 'right'
    });
    return batch.draw(texture, x, Gdx._height - y);
  };

  return BitmapFont;

})();

export default BitmapFont;
