// Generated by CoffeeScript 1.10.0
import Gdx from 'gdx/Gdx';
import TextureRegion from 'gdx/graphics/g2d/TextureRegion';

/*
 * @JSName("gdx.graphics.g2d.Sprite")
 */
var Sprite,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Sprite = (function(superClass) {
  extend(Sprite, superClass);

  function Sprite(texture) {
    Sprite.__super__.constructor.call(this, texture);
  }

  Sprite.prototype.getWidth = function() {
    return this.texture.sprite._texture.width;
  };

  Sprite.prototype.getHeight = function() {
    return this.texture.sprite._texture.height;
  };

  Sprite.prototype.setX = function(value) {};

  Sprite.prototype.setY = function(value) {};

  Sprite.prototype.setColor = function(red, green, blue, alpha) {};

  Sprite.prototype.setScale = function(x, y) {
    return this.texture.sprite.scale.set(x, y);
  };

  Sprite.prototype.setPosition = function(x, y) {
    return this.texture.sprite.position.set(x, Gdx.graphics.getHeight() - y - this.texture.sprite._texture.height);
  };

  Sprite.prototype.draw = function(batch) {
    return batch.draw(this, this.texture.sprite.position.x, this.texture.sprite.position.y);
  };

  return Sprite;

})(TextureRegion);

export default Sprite;
