// Generated by CoffeeScript 1.10.0
import Batch from 'gdx/graphics/g2d/Batch';

/*
 * @JSName("gdx.graphics.g2d.SpriteBatch")
 */
var SpriteBatch,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

SpriteBatch = (function(superClass) {
  extend(SpriteBatch, superClass);

  function SpriteBatch() {
    return SpriteBatch.__super__.constructor.apply(this, arguments);
  }

  return SpriteBatch;

})(Batch);

export default SpriteBatch;
