// Generated by CoffeeScript 1.10.0

/*
 * @JSName("gdx.graphics.g2d.TextureRegion")
 */
var TextureRegion;

TextureRegion = (function() {
  function TextureRegion(texture) {
    this.texture = texture;
  }

  return TextureRegion;

})();

export default TextureRegion;
