// Generated by CoffeeScript 1.10.0

/*
 * @JSName("gdx.graphics.g2d.TextureAtlas")
 */
var TextureAtlas;

TextureAtlas = (function() {
  function TextureAtlas(packFile) {
    this.packFile = packFile;
  }

  TextureAtlas.prototype.createSprite = function(name) {};

  return TextureAtlas;

})();

export default TextureAtlas;
