// Generated by CoffeeScript 1.10.0

/*
 * @JSName("gdx.scenes.scene2d.EventListener")
 */
var EventListener;

EventListener = (function() {
  function EventListener() {}

  return EventListener;

})();

export default EventListener;
