// Generated by CoffeeScript 1.10.0

/*
 * @JSName("gdx.scenes.scene2d.InputEvent")
 */
var InputEvent;

InputEvent = (function() {
  function InputEvent() {}

  return InputEvent;

})();

export default InputEvent;
