// Generated by CoffeeScript 1.10.0
import EventListener from 'gdx/scenes/scene2d/EventListener';

/*
 * @JSName("gdx.scenes.scene2d.InputListener")
 */
var InputListener,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

InputListener = (function(superClass) {
  extend(InputListener, superClass);

  function InputListener() {
    return InputListener.__super__.constructor.apply(this, arguments);
  }

  return InputListener;

})(EventListener);

export default InputListener;
