// Generated by CoffeeScript 1.10.0
import Scaling from 'gdx/utils/Scaling';
import ScalingViewport from 'gdx/utils/viewport/ScalingViewport';

/*
 * @JSName("gdx.utils.viewport.FillViewport")
 */
var FillViewport,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

FillViewport = (function(superClass) {
  extend(FillViewport, superClass);

  function FillViewport(worldWidth, worldHeight, camera) {
    FillViewport.__super__.constructor.call(this, Scaling.fill, worldWidth, worldHeight, camera);
  }

  return FillViewport;

})(ScalingViewport);

export default FillViewport;
