// Generated by CoffeeScript 1.10.0
import Scaling from 'gdx/utils/Scaling';
import ScalingViewport from 'gdx/utils/viewport/ScalingViewport';

/*
 * @JSName("gdx.utils.viewport.FitViewport")
 */
var FitViewport,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

FitViewport = (function(superClass) {
  extend(FitViewport, superClass);

  function FitViewport(worldWidth, worldHeight, camera) {
    FitViewport.__super__.constructor.call(this, Scaling.fit, worldWidth, worldHeight, camera);
  }

  return FitViewport;

})(ScalingViewport);

export default FitViewport;
