// Generated by CoffeeScript 1.10.0
import Viewport from 'gdx/utils/viewport/Viewport';
import OrthographicCamera from 'gdx/graphics/OrthographicCamera';

/*
 * @JSName("gdx.utils.viewport.ScalingViewport")
 */
var ScalingViewport,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ScalingViewport = (function(superClass) {
  extend(ScalingViewport, superClass);

  function ScalingViewport(scaling, worldWidth, worldHeight, camera) {
    ScalingViewport.__super__.constructor.call(this);
    this.scaling = scaling;
    this.worldWidth = worldWidth;
    this.worldHeight = worldHeight;
    this.camera = camera != null ? camera : new OrthographicCamera();
  }

  return ScalingViewport;

})(Viewport);

export default ScalingViewport;
