// Generated by CoffeeScript 1.10.0

/*
 * @JSName("gdx.utils.viewport.Viewport")
 */
var Viewport;

Viewport = (function() {
  function Viewport() {}

  Viewport.prototype.update = function(x, y) {};


  /*
  * applyCamera
  * 
  * Calls to the apply method of an object x map to 
  * calling x, i.e., x(...) instead of x.apply(...). 
  * @see https://www.scala-js.org/doc/interoperability/facade-types.html
   */

  Viewport.prototype.applyCamera = function() {};

  return Viewport;

})();

export default Viewport;
