// Generated by CoffeeScript 1.10.0

/*
 * @JSName("gdx.math.Vector3")
 */
var Vector3;

Vector3 = (function() {
  function Vector3() {
    this.set(0, 0, 0);
  }

  Vector3.prototype.set = function(x, y, z) {
    this.x = x;
    this.y = y;
    return this.z = z;
  };

  return Vector3;

})();

export default Vector3;
