// Generated by CoffeeScript 1.10.0

/*
 * @JSName("gdx.scenes.scene2d.utils.ClickListener")
 */
var ClickListener;

ClickListener = (function() {
  function ClickListener() {}

  ClickListener.prototype.clicked = function(event, x, y) {};

  return ClickListener;

})();

export default ClickListener;
