// Generated by CoffeeScript 1.10.0
var FileHandle;

FileHandle = (function() {
  function FileHandle(path) {
    this.path = path;
  }

  FileHandle.prototype.readString = function() {
    return Gdx._internal[this.path].xhr.responseText;
  };

  return FileHandle;

})();

export default FileHandle;
