// Generated by CoffeeScript 1.10.0
import FileHandle from 'gdx/files/FileHandle';

/*
 * @JSName("gdx.Files")
 */
var Files;

Files = (function() {
  function Files() {}

  Files.prototype.internal = function(path) {
    return new FileHandle(path);
  };

  return Files;

})();

export default Files;
