// Generated by CoffeeScript 1.10.0

/*
 * @JSName("Gdx")
 */
var Gdx;

Gdx = (function() {
  function Gdx() {}

  Gdx.app = null;

  Gdx.graphics = null;

  Gdx.audio = null;

  Gdx.files = null;

  Gdx.input = null;

  Gdx.get = null;

  Gdx.gl = null;

  Gdx._resources = null;

  Gdx._internal = null;

  Gdx._renderer = null;

  Gdx._stage = null;

  Gdx._scaling = 1;

  Gdx._scaleX = 1;

  Gdx._scaleY = 1;

  Gdx._height = 0;

  Gdx._width = 0;

  return Gdx;

})();

export default Gdx;
