// Generated by CoffeeScript 1.10.0
import GL20 from 'gdx/graphics/GL20';
import Gdx from  'gdx/Gdx';

/*
 * @JSName("gdx.Graphics")
 */
var Graphics;

Graphics = (function() {
  function Graphics(config) {
    this.config = config;
    this.gl20 = new GL20();
    this.frameId = -1;
    this.lastTime = 0;
    this.deltaTime = 0;
    this.frames = 0;
    this.time = 0;
    this.fps = 0;
  }

  Graphics.prototype.getDeltaTime = function() {
    return this.deltaTime;
  };

  Graphics.prototype.getWidth = function() {
    return this.config.width;
  };

  Graphics.prototype.getHeight = function() {
    return this.config.height;
  };

  Graphics.prototype.getDensity = function() {
    return window.devicePixelRatio;
  };

  Graphics.prototype.setupDisplay = function() {
    return Gdx.gl = this.gl20;
  };

  Graphics.prototype.update = function(time) {
    if (this.lastTime <= 0) {
      this.lastTime = time;
      return;
    }
    this.deltaTime = (time - this.lastTime) * .001;
    this.lastTime = time;
    this.time += this.deltaTime;
    this.frames++;
    if (this.time > 1) {
      this.fps = this.frames;
      this.time = 0;
      return this.frames = 0;
    }
  };

  return Graphics;

})();

export default Graphics;
