// Generated by CoffeeScript 1.10.0

/*
 * @JSName("gdx.JsApplicationConfiguration")
 */
var JsApplicationConfiguration;

JsApplicationConfiguration = (function() {
  function JsApplicationConfiguration() {
    this.height = 480;
    this.width = 640;
    this.fullscreen = false;
    this.title = null;
  }

  return JsApplicationConfiguration;

})();

export default JsApplicationConfiguration;
