// Generated by CoffeeScript 1.10.0
import Vector3 from 'gdx/math/Vector3';

/*
 * @JSName("gdx.graphics.Camera")
 */
var Camera;

Camera = (function() {
  function Camera(viewportWidth, viewportHeight) {
    this.viewportWidth = viewportWidth;
    this.viewportHeight = viewportHeight;
    this.position = new Vector3();
  }

  Camera.prototype.update = function() {};

  return Camera;

})();

export default Camera;
