// Generated by CoffeeScript 1.10.0
import Gdx from 'gdx/Gdx';

/*
 * @JSName("gdx.graphics.GL20")
 */
var GL20;

GL20 = (function() {
  function GL20() {}

  GL20.GL_COLOR_BUFFER_BIT = 0x00004000;

  GL20.GL_NEAREST = 0x2600;

  GL20.GL_LINEAR = 0x2601;

  GL20.GL_LINEAR_MIPMAP_LINEAR = 0x2703;

  GL20.GL_NEAREST_MIPMAP_NEAREST = 0x2700;

  GL20.GL_LINEAR_MIPMAP_NEAREST = 0x2701;

  GL20.GL_NEAREST_MIPMAP_LINEAR = 0x2702;

  GL20.GL_LINEAR_MIPMAP_LINEAR = 0x2703;

  GL20.prototype.glClearColor = function(red, green, blue, alpha) {
    var hexColor;
    hexColor = (1 << 24) + (red * 255 << 16) + (green * 255 << 8) + blue * 255;
    return Gdx._renderer.backgroundColor = hexColor;
  };

  GL20.prototype.glClear = function(mask) {};

  return GL20;

})();

export default GL20;
