// Generated by CoffeeScript 1.10.0
import Camera from 'gdx/graphics/Camera';

/*
 * @JSName("gdx.graphics.OrthographicCamera")
 */
var OrthographicCamera,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

OrthographicCamera = (function(superClass) {
  extend(OrthographicCamera, superClass);

  function OrthographicCamera(viewportWidth, viewportHeight) {
    OrthographicCamera.__super__.constructor.call(this, viewportWidth, viewportHeight);
    this.combined = null;
  }

  OrthographicCamera.prototype.update = function() {};

  return OrthographicCamera;

})(Camera);

export default OrthographicCamera;
