// Generated by CoffeeScript 1.10.0
import GL20 from 'gdx/graphics/GL20';
import Gdx from 'gdx/Gdx';

/*
 * @JSName("gdx.graphics.Texture")
 */
var Texture, pixi;

pixi = require('pixi');

Texture = (function() {
  Texture.uniqueId = 0;

  Texture.TextureFilter = {
    Nearest: GL20.GL_NEAREST,
    Linear: GL20.GL_LINEAR,
    MipMap: GL20.GL_LINEAR_MIPMAP_LINEAR,
    MipMapNearestNearest: GL20.GL_NEAREST_MIPMAP_NEAREST,
    MipMapLinearNearest: GL20.GL_LINEAR_MIPMAP_NEAREST,
    MipMapNearestLinear: GL20.GL_NEAREST_MIPMAP_LINEAR,
    MipMapLinearLinear: GL20.GL_LINEAR_MIPMAP_LINEAR
  };

  function Texture(path) {
    if (typeof path === 'string') {
      this.path = Gdx._resources[path] != null ? Gdx._resources[path].url : path;
    } else {
      this.path = path.path;
    }
    this.sprite = pixi.Sprite.fromImage(this.path);
    this.id = Texture.uniqueId++;
  }

  Texture.prototype.setFilter = function(minFilter, magFilter) {};

  return Texture;

})();

export default Texture;
