// Generated by CoffeeScript 1.10.0

/*
 * AMD Module self loader
 * fallback to global require
 *
 */
var define;

define = (function(global, modules) {

  /*
   *  require module
   *
   * shims for late loading globals
   * fallback to global require 
   * 
   * @param name
   * @returns module reference for name
   */
  var require;
  require = function(name) {
    if (modules[name] != null) {
      return modules[name].exports;
    } else {
      return global != null ? global.require(name) : void 0;
    }
  };

  /*
   *  define module
   * 
   * @param name of module
   * @param deps for module
   * @param callback to the module cide itself
   */
  define = function(name, deps, callback) {
    var args;
    modules[name] = {
      id: name,
      exports: {}
    };
    args = [require, modules[name].exports];
    deps.slice(2).forEach(function(dep) {
      return args.push(modules[dep].exports);
    });
    callback.apply(modules[name].exports, args);
  };

  /*
   *  define,global
   * 
   * @param name
   * @param module
   */
  define.global = function(name, module) {
    return global[name] = module;
  };

  /*
   *  define,register
   * 
   * @param name
   * @param exports
   */
  define.register = function(name, exports) {
    return modules[name] = {
      id: name,
      exports: {}
    };
  };
  define.env = modules;
  return define;
})(this, (define != null ? define.env : void 0) || {});
