// Generated by CoffeeScript 1.10.0
System["import"]('gdx').then(function(gdx) {
  console.log('gdx loaded');
  return window['gdx'] = gdx["default"];
}, function(err) {
  return console.log(err);
});
