// Generated by CoffeeScript 1.10.0

/*
 * @JSName("gdx.utils.Scaling")
 */
var Scaling;

Scaling = (function() {
  function Scaling() {}

  Scaling[Scaling.fit = 0] = 'fit';

  Scaling[Scaling.fill = 1] = 'fill';

  Scaling[Scaling.fillX = 2] = 'fillX';

  Scaling[Scaling.fillY = 3] = 'fillY';

  Scaling[Scaling.stretch = 4] = 'stretch';

  Scaling[Scaling.stretchX = 5] = 'stretchX';

  Scaling[Scaling.stretchY = 6] = 'stretchY';

  Scaling[Scaling.none = 7] = 'none';

  return Scaling;

})();

export default Scaling;
